Repository AY2021S1-CS2113T-F12-3/tp, pull requests merged in 2020-10, with the labels that each got.

#12 Add basic interfaces as skeleton
  src/main/java/seedu/duke/CommandInterface.java
  src/main/java/seedu/duke/HintInterface.java
  src/main/java/seedu/duke/OptionInterface.java
  src/main/java/seedu/duke/OptionListInterface.java
  src/main/java/seedu/duke/ParserInterface.java
  src/main/java/seedu/duke/QuestionInterface.java
  src/main/java/seedu/duke/QuestionListInterface.java
  src/main/java/seedu/duke/QuizInterface.java
  src/main/java/seedu/duke/StorageInterface.java
  src/main/java/seedu/duke/TopicInterface.java
  src/main/java/seedu/duke/TopicListInterface.java
  src/main/java/seedu/duke/UiInterface.java
Labels: priority.High, type.Task

#13 Add storage class
  .gitignore
  build.gradle
  data/test/empty.json
  data/test/example.json
  src/main/java/seedu/duke/CommandInterface.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageInterface.java
  src/test/java/seedu/duke/StorageTest.java
Labels: priority.High, type.Task

#22 Add Question class and Hint class
  src/main/java/seedu/duke/QuestionListInterface.java
  src/main/java/seedu/duke/TopicInterface.java
  src/main/java/seedu/duke/UiInterface.java
  src/main/java/seedu/duke/hint/Hint.java
  src/main/java/seedu/duke/hint/HintInterface.java
  src/main/java/seedu/duke/question/Question.java
  src/main/java/seedu/duke/question/QuestionInterface.java
  src/main/java/seedu/duke/question/QuestionList.java
  src/main/java/seedu/duke/question/QuestionListInterface.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/hint/HintTest.java
Labels: priority.High

#23 Add Option Class
  docs/AboutUs.md
  src/main/java/seedu/duke/UiInterface.java
  src/main/java/seedu/duke/option/Option.java
  src/main/java/seedu/duke/option/OptionInterface.java
  src/main/java/seedu/duke/option/OptionList.java
  src/main/java/seedu/duke/option/OptionListInterface.java
  src/main/java/seedu/duke/question/Question.java
  src/main/java/seedu/duke/question/QuestionInterface.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: priority.High

#24 Add user interface
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/ui/UiInterface.java
Labels: priority.High

#33 Change package name
  build.gradle
  src/main/java/seedu/eduke8/CommandInterface.java
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/ParserInterface.java
  src/main/java/seedu/eduke8/QuizInterface.java
  src/main/java/seedu/eduke8/TopicInterface.java
  src/main/java/seedu/eduke8/TopicListInterface.java
  src/main/java/seedu/eduke8/hint/Hint.java
  src/main/java/seedu/eduke8/hint/HintInterface.java
  src/main/java/seedu/eduke8/option/Option.java
  src/main/java/seedu/eduke8/option/OptionInterface.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/option/OptionListInterface.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/question/QuestionInterface.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuestionListInterface.java
  src/main/java/seedu/eduke8/storage/Storage.java
  src/main/java/seedu/eduke8/storage/StorageInterface.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/main/java/seedu/eduke8/ui/UiInterface.java
  src/test/java/seedu/eduke8/Eduke8Test.java
  src/test/java/seedu/eduke8/StorageTest.java
  src/test/java/seedu/eduke8/hint/HintTest.java
Labels: priority.Medium

#34 Add Topic and TopicList classes
  src/main/java/seedu/eduke8/CommandInterface.java
  src/main/java/seedu/eduke8/TopicListInterface.java
  src/main/java/seedu/eduke8/storage/Storage.java
  src/main/java/seedu/eduke8/storage/StorageInterface.java
  src/main/java/seedu/eduke8/topic/Topic.java
  src/main/java/seedu/eduke8/topic/TopicInterface.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/topic/TopicListInterface.java
  src/test/java/seedu/eduke8/StorageTest.java
Labels: priority.High

#38 Add quiz class
  src/main/java/seedu/eduke8/QuizInterface.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuestionListInterface.java
  src/main/java/seedu/eduke8/quiz/Quiz.java
  src/main/java/seedu/eduke8/quiz/QuizInterface.java
Labels: priority.High

#39 Added the Parser class
  src/main/java/seedu/eduke8/Parser.java
  src/main/java/seedu/eduke8/ParserInterface.java
Labels: priority.High

#44 Implement the storage load method
  src/main/java/seedu/eduke8/storage/Storage.java
  src/main/java/seedu/eduke8/topic/Topic.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/test/java/seedu/eduke8/StorageTest.java
Labels: priority.High

#46 Add Quiz constructor to Parser
  src/main/java/seedu/eduke8/Parser.java
  src/main/java/seedu/eduke8/ParserInterface.java
  src/main/java/seedu/eduke8/quiz/Quiz.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/topic/TopicListInterface.java
Labels: priority.High

#47 Add eduke8
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/Parser.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/main/java/seedu/eduke8/ui/UiInterface.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#51 Attempt to simplify interfaces into more common ones
  src/main/java/seedu/eduke8/Command.java
  src/main/java/seedu/eduke8/CommandInterface.java
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/Parser.java
  src/main/java/seedu/eduke8/ParserInterface.java
  src/main/java/seedu/eduke8/common/Displayable.java
  src/main/java/seedu/eduke8/common/DisplayableList.java
  src/main/java/seedu/eduke8/hint/Hint.java
  src/main/java/seedu/eduke8/hint/HintInterface.java
  src/main/java/seedu/eduke8/option/Option.java
  src/main/java/seedu/eduke8/option/OptionInterface.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/option/OptionListInterface.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/Parser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/question/QuestionInterface.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuestionListInterface.java
  src/main/java/seedu/eduke8/quiz/Quiz.java
  src/main/java/seedu/eduke8/quiz/QuizInterface.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/main/java/seedu/eduke8/storage/Storage.java
  src/main/java/seedu/eduke8/storage/StorageInterface.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/topic/Topic.java
  src/main/java/seedu/eduke8/topic/TopicInterface.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/topic/TopicListInterface.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/main/java/seedu/eduke8/ui/UiInterface.java
  src/test/java/seedu/eduke8/StorageTest.java
  src/test/java/seedu/eduke8/hint/HintTest.java
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
Labels: priority.High

#56 Add commands for quiz parser
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/command/Command.java
  src/main/java/seedu/eduke8/command/HintCommand.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/Parser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/test/java/seedu/eduke8/command/AnswerCommandTest.java
  src/test/java/seedu/eduke8/command/HintCommandTest.java
Labels: priority.High

#59 Add QuizQuestionsManager class
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/exception/Eduke8Exception.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/Parser.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/main/java/seedu/eduke8/quiz/Quiz.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
Labels: priority.High

#62 Add a command class for each command available in MenuParser.
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/command/AboutCommand.java
  src/main/java/seedu/eduke8/command/Command.java
  src/main/java/seedu/eduke8/command/ExitCommand.java
  src/main/java/seedu/eduke8/command/HelpCommand.java
  src/main/java/seedu/eduke8/command/IncorrectCommand.java
  src/main/java/seedu/eduke8/command/QuizCommand.java
  src/main/java/seedu/eduke8/command/TextbookCommand.java
  src/main/java/seedu/eduke8/command/TopicsCommand.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#63 Add Junit tests for questions
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/test/java/seedu/eduke8/question/QuestionListTest.java
  src/test/java/seedu/eduke8/question/QuestionTest.java
  src/test/java/seedu/eduke8/question/QuizQuestionsManagerTest.java
Labels: priority.High

#64 Add JUnit test for SingleTopicQuiz
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/test/java/seedu/eduke8/quiz/SingleTopicQuizTest.java
Labels: priority.High

#71 Fix quiz logic
  .gitignore
  data/main/topics.json
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/main/topics.json
  text-ui-test/input.txt
  text-ui-test/runtest.bat
Labels: priority.High

#72 Add log storage
  .gitignore
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/main/java/seedu/eduke8/storage/LocalStorage.java
  src/main/java/seedu/eduke8/storage/LogStorage.java
  src/main/java/seedu/eduke8/storage/Storage.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
Labels: priority.High

#75 Add logging and assertions
  build.gradle
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/command/HintCommand.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/main/java/seedu/eduke8/storage/LocalStorage.java
  src/main/java/seedu/eduke8/storage/LogStorage.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
Labels: priority.Medium

#76 Add 5 questions to revision control topic
  data/main/topics.json
Labels: priority.Medium

#79 Enhance Ui to do error handling
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/command/IncorrectCommand.java
  src/main/java/seedu/eduke8/command/QuizCommand.java
  src/main/java/seedu/eduke8/exception/Eduke8Exception.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#87 Add IOOB exception
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
Labels: severity.High, type.Bug

#82 Add MenuParserTest and QuizParserTest.
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
  src/test/java/seedu/eduke8/parser/QuizParserTest.java
Labels: priority.High

#88 Change wrong answer response
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
Labels: type.Enhancement

#90 Enhance ui to improve user experience
  src/main/java/seedu/eduke8/exception/Eduke8Exception.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement

#100 Update docs using our discussion notes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/team/anqi.md
  docs/team/joel.md
  docs/team/joseph.md
  docs/team/zhiyou.md
Labels: priority.High

#106 Add LogStorageTest to test log file creation
  src/main/java/seedu/eduke8/storage/LocalStorage.java
  src/main/java/seedu/eduke8/storage/LogStorage.java
  src/test/java/seedu/eduke8/storage/LogStorageTest.java
Labels: priority.Medium, type.Enhancement

#115 Add images
  docs/UserGuide.md
  docs/images/about.png
  docs/images/exit.png
  docs/images/help.png
  docs/images/hint.png
  docs/images/quiz.png
  docs/images/textbook.png
  docs/images/topics.png
  docs/images/welcome.png
Labels: priority.High

#116 Add class diagram and sequence diagram for loading data
  docs/DeveloperGuide.md
  docs/diagrams/TopicsStorage.drawio
  docs/diagrams/TopicsStorage_load.drawio
  docs/images/TopicsStorage.png
  docs/images/TopicsStorage_load.png
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
Labels: priority.High

#118 Add an Explanation Class
  data/main/topics.json
  data/test/example.json
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/explanation/Explanation.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/command/AnswerCommandTest.java
  src/test/java/seedu/eduke8/explanation/ExplanationTest.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
  src/test/java/seedu/eduke8/parser/QuizParserTest.java
  src/test/java/seedu/eduke8/question/QuestionListTest.java
  src/test/java/seedu/eduke8/question/QuestionTest.java
  src/test/java/seedu/eduke8/question/QuizQuestionsManagerTest.java
  src/test/java/seedu/eduke8/topic/TopicListTest.java
  src/test/java/seedu/eduke8/topic/TopicTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/main/topics.json
Labels: priority.High, type.Task

#122 Remove add and delete methods
  src/main/java/seedu/eduke8/common/DisplayableList.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/test/java/seedu/eduke8/command/AnswerCommandTest.java
  src/test/java/seedu/eduke8/command/HintCommandTest.java
  src/test/java/seedu/eduke8/option/OptionListTest.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
  src/test/java/seedu/eduke8/parser/QuizParserTest.java
  src/test/java/seedu/eduke8/question/QuestionListTest.java
  src/test/java/seedu/eduke8/question/QuestionTest.java
  src/test/java/seedu/eduke8/question/QuizQuestionsManagerTest.java
  src/test/java/seedu/eduke8/topic/TopicListTest.java
  src/test/java/seedu/eduke8/topic/TopicTest.java
Labels: priority.Medium

#125 Update Developer Guide and add user stories of V1.0 and V2.0
  docs/DeveloperGuide.md
  docs/images/Option.png
  docs/images/PrintQuizStartPage.png
Labels: priority.High, type.Task

#127 Add notes class + Updated Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/TopicListAndNotes.drawio
  docs/diagrams/TopicListSampleSequence.drawio
  docs/images/TopicListAndNotes.png
  docs/images/TopicListSampleSequence.png
  src/main/java/seedu/eduke8/note/Note.java
  src/main/java/seedu/eduke8/note/NoteList.java
  src/main/java/seedu/eduke8/topic/Topic.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/note/NoteListTest.java
  src/test/java/seedu/eduke8/note/NoteTest.java
Labels: priority.High, type.Enhancement, type.Task

#126 Add feature that allows for the number of questions and topic name in…
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#130 Edit UserGuide and DeveloperGuide and Ui
  data/main/topics.json
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/QuizQuestionsManager_setQuizQuestions.drawio
  docs/images/QuizQuestionsManager_setQuizQuestions.png
  docs/images/about.png
  docs/images/exit.png
  docs/images/help.png
  docs/images/hint.png
  docs/images/quiz.png
  docs/images/quiz_correct.png
  docs/images/quiz_end.png
  docs/images/quiz_wrong.png
  docs/images/textbook.png
  docs/images/topics.png
  docs/images/welcome.png
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#131 Fix quiz assertion error and cleanup Junits
  src/main/java/seedu/eduke8/command/QuizCommand.java
  src/main/java/seedu/eduke8/common/DisplayableList.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/main/java/seedu/eduke8/storage/LogStorage.java
  src/main/java/seedu/eduke8/storage/Storage.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/test/java/seedu/eduke8/Eduke8Test.java
  src/test/java/seedu/eduke8/command/AnswerCommandTest.java
  src/test/java/seedu/eduke8/command/HintCommandTest.java
  src/test/java/seedu/eduke8/explanation/ExplanationTest.java
  src/test/java/seedu/eduke8/hint/HintTest.java
  src/test/java/seedu/eduke8/note/NoteListTest.java
  src/test/java/seedu/eduke8/option/OptionListTest.java
  src/test/java/seedu/eduke8/option/OptionTest.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
  src/test/java/seedu/eduke8/parser/QuizParserTest.java
  src/test/java/seedu/eduke8/question/QuestionListTest.java
  src/test/java/seedu/eduke8/question/QuestionTest.java
  src/test/java/seedu/eduke8/question/QuizQuestionsManagerTest.java
  src/test/java/seedu/eduke8/quiz/SingleTopicQuizTest.java
  src/test/java/seedu/eduke8/storage/LogStorageTest.java
  src/test/java/seedu/eduke8/topic/TopicListTest.java
  src/test/java/seedu/eduke8/topic/TopicTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug

#135 Add table of contents to UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#139 Clean up Ui
  docs/images/PrintQuizStartPage.png
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/command/BookmarkCommand.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#136 Add stats feature (partial)
  docs/DeveloperGuide.md
  src/main/java/seedu/eduke8/bookmark/BookmarkList.java
  src/main/java/seedu/eduke8/command/AboutCommand.java
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/command/BookmarkCommand.java
  src/main/java/seedu/eduke8/command/ExitCommand.java
  src/main/java/seedu/eduke8/command/HelpCommand.java
  src/main/java/seedu/eduke8/command/HintCommand.java
  src/main/java/seedu/eduke8/command/IncorrectCommand.java
  src/main/java/seedu/eduke8/command/QuizCommand.java
  src/main/java/seedu/eduke8/command/StatsCommand.java
  src/main/java/seedu/eduke8/command/TextbookCommand.java
  src/main/java/seedu/eduke8/command/TopicsCommand.java
  src/main/java/seedu/eduke8/option/OptionList.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/stats/Stats.java
  src/main/java/seedu/eduke8/stats/StatsCalculator.java
  src/main/java/seedu/eduke8/stats/TopicalStatsCalculator.java
  src/main/java/seedu/eduke8/stats/UserStatsCalculator.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#140 Edit UG
  docs/UserGuide.md
Labels: priority.High

#142 Add diagrams and details for architecture and UserStorage
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Architecture.drawio
  docs/diagrams/TopicsStorage.drawio
  docs/diagrams/UserStorage.drawio
  docs/diagrams/UserStorage_save.drawio
  docs/images/Architecture.png
  docs/images/TopicsStorage.png
  docs/images/UserStorage.png
  docs/images/UserStorage_save.png
Labels: priority.High

#143 Add Stats Class Diagram
  docs/DeveloperGuide.md
  docs/diagrams/QuizQuestionsManager.drawio
  docs/diagrams/Stats.drawio
  docs/diagrams/Stats_showPointsEarned.drawio
  docs/images/QuizQuestionsManager.png
  docs/images/Stats.png
  src/main/java/seedu/eduke8/common/EditableList.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/stats/Stats.java
  src/main/java/seedu/eduke8/stats/StatsCalculator.java
  src/main/java/seedu/eduke8/stats/TopicalStatsCalculator.java
  src/main/java/seedu/eduke8/stats/UserStatsCalculator.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#145 Add sequence diagram for stats feature
  docs/DeveloperGuide.md
  docs/diagrams/Stats.drawio
  docs/diagrams/Stats_showPointsEarned.drawio
  docs/images/Stats.png
  docs/images/Stats_showPointsEarned.png
Labels: priority.High

#146 Add stats feature to User Guide
  docs/README.md
  docs/UserGuide.md
  docs/images/stats_No_Progress.png
  docs/images/stats_Some_Progress.png
  src/main/java/seedu/eduke8/stats/StatsCalculator.java
Labels: priority.High

#147 Add JUnit Tests for UserStorage
  data/test/missing_key.json
  data/test/save.json
  data/test/topics.json
  data/test/user.json
  data/test/wrong_format.json
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/storage/LocalStorage.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/storage/UserStorage.java
  src/test/java/seedu/eduke8/Eduke8Test.java
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
  src/test/java/seedu/eduke8/storage/UserStorageTest.java
Labels: priority.High

#144 Implemented NoteCommands + made minor adjustments to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/TopicListAndNotes.png
  docs/images/TopicListSampleSequence.png
  src/main/java/seedu/eduke8/command/NoteCommand.java
  src/main/java/seedu/eduke8/note/Note.java
  src/main/java/seedu/eduke8/note/NoteList.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/storage/UserStorage.java
  src/main/java/seedu/eduke8/topic/Topic.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/note/NoteListTest.java
  src/test/java/seedu/eduke8/note/NoteTest.java
Labels: priority.High, type.Task

#148 Add the explanation for Revision Control questions
  data/main/topics.json
Labels: priority.Medium

#150 Add timer to each question
  src/main/java/seedu/eduke8/command/IncompleteCommand.java
  src/main/java/seedu/eduke8/command/QuizCommand.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/Eduke8Test.java
  src/test/java/seedu/eduke8/command/QuizCommandTest.java
  src/test/java/seedu/eduke8/parser/QuizParserTest.java
  src/test/java/seedu/eduke8/quiz/SingleTopicQuizTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement

#153 Add JUnit tests for Stats classes
  docs/diagrams/Stats.drawio
  docs/images/Stats.png
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/main/java/seedu/eduke8/stats/Stats.java
  src/main/java/seedu/eduke8/stats/StatsCalculator.java
  src/main/java/seedu/eduke8/stats/TopicalStatsCalculator.java
  src/test/java/seedu/eduke8/Eduke8Test.java
  src/test/java/seedu/eduke8/hint/HintTest.java
  src/test/java/seedu/eduke8/question/QuestionListTest.java
  src/test/java/seedu/eduke8/question/QuestionTest.java
  src/test/java/seedu/eduke8/question/QuizQuestionsManagerTest.java
  src/test/java/seedu/eduke8/stats/StatsCalculatorTest.java
  src/test/java/seedu/eduke8/stats/StatsTest.java
  src/test/java/seedu/eduke8/stats/TopicalStatsCalculatorTest.java
  src/test/java/seedu/eduke8/stats/UserStatsCalculatorTest.java
Labels: priority.High

#155 Add javadocs for Question classes
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/main/java/seedu/eduke8/question/QuizQuestionsManager.java
  src/main/java/seedu/eduke8/stats/Stats.java
  src/main/java/seedu/eduke8/storage/LogStorage.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#158 Fix for quiz windows but breaks for WSL
  src/main/java/seedu/eduke8/command/AnswerCommand.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug

#165 Update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/OptionSequence.png
  docs/images/help.png
  docs/images/quiz.png
  docs/images/quiz_correct.png
  docs/images/quiz_times_up.png
  docs/images/quiz_wrong.png
  docs/images/topics.png
Labels: priority.High

#167 Enhance DG based on peer review
  docs/DeveloperGuide.md
  docs/diagrams/QuizQuestionsManager.drawio
  docs/diagrams/QuizQuestionsManager_setQuizQuestions.drawio
  docs/images/QuizQuestionsManager.png
  docs/images/QuizQuestionsManager_setQuizQuestions.png
Labels: priority.High
