Repository AY2021S1-CS2113T-F12-3/tp, pull requests merged in 2020-11, with the labels that each got.

#159 Improve SingleTopicQuiz and UserStorage code coverage
  data/test/save.json
  data/test/user.json
  docs/UserGuide.md
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/bookmark/BookmarkList.java
  src/test/java/seedu/eduke8/Eduke8Test.java
  src/test/java/seedu/eduke8/command/AnswerCommandTest.java
  src/test/java/seedu/eduke8/command/BookmarkCommandTest.java
  src/test/java/seedu/eduke8/command/ExitCommandTest.java
  src/test/java/seedu/eduke8/command/HintCommandTest.java
  src/test/java/seedu/eduke8/command/QuizCommandTest.java
  src/test/java/seedu/eduke8/hint/HintTest.java
  src/test/java/seedu/eduke8/note/NoteListTest.java
  src/test/java/seedu/eduke8/note/NoteTest.java
  src/test/java/seedu/eduke8/option/OptionListTest.java
  src/test/java/seedu/eduke8/option/OptionTest.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
  src/test/java/seedu/eduke8/parser/QuizParserTest.java
  src/test/java/seedu/eduke8/question/QuestionListTest.java
  src/test/java/seedu/eduke8/question/QuestionTest.java
  src/test/java/seedu/eduke8/question/QuizQuestionsManagerTest.java
  src/test/java/seedu/eduke8/quiz/SingleTopicQuizTest.java
  src/test/java/seedu/eduke8/stats/StatsCalculatorTest.java
  src/test/java/seedu/eduke8/stats/StatsTest.java
  src/test/java/seedu/eduke8/stats/TopicalStatsCalculatorTest.java
  src/test/java/seedu/eduke8/stats/UserStatsCalculatorTest.java
  src/test/java/seedu/eduke8/storage/LogStorageTest.java
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
  src/test/java/seedu/eduke8/storage/UserStorageTest.java
  src/test/java/seedu/eduke8/topic/TopicTest.java
Labels: priority.Medium

#208 Enhance timer
  .github/workflows/gradle.yml
  src/main/java/seedu/eduke8/command/IncompleteCommand.java
  src/main/java/seedu/eduke8/command/QuizCommand.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/parser/QuizParser.java
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
  src/main/java/seedu/eduke8/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High, type.Bug

#209 Enhance Stats DG according to comments given
  docs/diagrams/Stats.drawio
  docs/diagrams/Stats_showPointsEarned.drawio
  docs/images/Stats.png
  docs/images/Stats_showPointsEarned.png
Labels: priority.High

#169 Add instructions on how to use bookmarks into UG.
  docs/UserGuide.md
Labels: priority.High, type.Task

#215 Add PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/kingston.md
  docs/team/kstonekuan.md
Labels: priority.High

#217 Add PPP
  docs/AboutUs.md
  docs/team/kstonekuan.md
  docs/team/zhi-you.md
  docs/team/zhiyou.md
Labels: priority.High

#219 Add my ppp
  docs/AboutUs.md
  docs/team/joel.md
  docs/team/joelngyx.md
Labels: priority.Medium

#207 Update ugdg
  data/main/topics.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/NoteCommandSequence.png
  docs/images/NoteListClassDiagram.png
  docs/images/TopicListAndNotes.png
  docs/images/TopicListClassDiagram.png
  docs/images/TopicListSampleSequence.png
  docs/images/noteadd.png
  docs/images/notedelete.png
  docs/images/notelist.png
  docs/images/topiclistsequence.png
  docs/team/kingston.md
  docs/team/zhiyou.md
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/eduke8/ui/Ui.java
Labels: priority.Medium, type.Enhancement

#221 Minor change to stats sequence diagram
  docs/diagrams/Stats_showPointsEarned.drawio
  docs/images/Stats_showPointsEarned.png
  docs/team/zhiyou.md
Labels: priority.High

#223 Update PPP
  docs/AboutUs.md
  docs/team/anqi20.md
  src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java
Labels: priority.High

#222 Update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Option.png
  docs/images/OptionSequence.png
  docs/images/PrintQuizStartPage.png
  docs/images/Timer.png
  docs/images/Ui.png
  docs/images/about.png
  docs/images/bookmark_store.png
  docs/images/data_loaded.png
  docs/images/data_loading.png
  docs/images/data_saved.png
  docs/images/data_saving.png
  docs/images/exit.png
  docs/images/help.png
  docs/images/hint.png
  docs/images/noteadd.png
  docs/images/notedelete.png
  docs/images/notelist.png
  docs/images/question_end.png
  docs/images/quiz_correct.png
  docs/images/quiz_end.png
  docs/images/quiz_times_up.png
  docs/images/quiz_wrong.png
  docs/images/stats_No_Progress.png
  docs/images/stats_Some_Progress.png
  docs/images/textbook.png
  docs/images/topics.png
  docs/images/welcome.png
Labels: priority.High

#224 Update storage UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TopicsStorage.drawio
  docs/diagrams/UserStorage.drawio
  docs/diagrams/UserStorage_load.drawio
  docs/diagrams/UserStorage_save.drawio
  docs/images/TopicsStorage.png
  docs/images/UserStorage.png
  docs/images/UserStorage_load.png
  docs/images/UserStorage_save.png
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/storage/UserStorage.java
Labels: priority.Medium, severity.Low, type.Bug

#229 Fix logic issue with one of the if statements that checks quiz command parameters.
  src/main/java/seedu/eduke8/parser/MenuParser.java
Labels: priority.High

#233 Fix bugs to stats logic and to DG as per discussed
  docs/diagrams/Parser Sample Sequence_.drawio
  docs/diagrams/Parser_Sample_Sequence_.drawio
  docs/diagrams/QuizQuestionsManager.drawio
  docs/diagrams/QuizQuestionsManager_setQuizQuestions.drawio
  docs/diagrams/Stats.drawio
  docs/images/ParserSampleSequence.jpg
  docs/images/ParserSampleSequence.png
  docs/images/QuizQuestionsManager.png
  docs/images/QuizQuestionsManager_setQuizQuestions.png
  docs/images/Stats.png
  src/main/java/seedu/eduke8/hint/Hint.java
  src/main/java/seedu/eduke8/question/Question.java
  src/main/java/seedu/eduke8/stats/StatsCalculator.java
  src/main/java/seedu/eduke8/stats/UserStatsCalculator.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/stats/StatsCalculatorTest.java
Labels: priority.High

#237 Fix topics storage load strange data
  data/test/blank_question_description.json
  data/test/blank_topic_title.json
  data/test/duplicate_questions.json
  data/test/duplicate_topics.json
  docs/UserGuide.md
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
Labels: severity.Low, type.Bug

#228 Update ppp
  docs/AboutUs.md
  docs/team/joelngyx.md
Labels: priority.Medium

#238 Remove catching of duplicate question
  data/test/duplicate_questions.json
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
Labels: severity.Medium, type.Bug

#240 Update the UG
  data/main/topics.json
  docs/images/stats_Some_Progress.png
Labels: priority.Medium

#232 Add error handling for bookmark delete function.
  src/main/java/seedu/eduke8/bookmark/BookmarkList.java
  src/main/java/seedu/eduke8/command/BookmarkCommand.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/bookmark/BookmarkListTest.java
  src/test/java/seedu/eduke8/command/BookmarkCommandTest.java
  src/test/java/seedu/eduke8/parser/MenuParserTest.java
Labels: priority.High

#243 Update Bookmark Features
  docs/UserGuide.md
  docs/images/bookmark_delete.jpg
  docs/images/bookmark_delete.png
  docs/images/bookmark_list.jpg
  docs/images/bookmark_list.png
  docs/images/help.png
  src/main/java/seedu/eduke8/command/BookmarkCommand.java
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/ui/Ui.java
Labels: priority.High

#246 Catch the errors more strictly for quiz parsing
  src/main/java/seedu/eduke8/parser/MenuParser.java
Labels: severity.VeryLow, type.Bug

#245 Edit manual testing for DG
  docs/DeveloperGuide.md
Labels: priority.High

#249 Don't allow duplicate titles regardless of case
  data/test/duplicate_topics.json
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
Labels: severity.Low, type.Bug

#250 Update bookmarklist functionallity to markAsNotBookmarked once removed from bookmarkList.
  src/main/java/seedu/eduke8/command/BookmarkCommand.java
  src/main/java/seedu/eduke8/question/Question.java
Labels: severity.High

#251 Fix user storage loading same questions into bookmarks
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/storage/UserStorage.java
Labels: severity.Low, type.Bug

#252 Fix final bugs
  docs/images/quiz.png
  src/main/java/seedu/eduke8/exception/ExceptionMessages.java
  src/main/java/seedu/eduke8/parser/MenuParser.java
  src/main/java/seedu/eduke8/ui/Ui.java
Labels: priority.High

#256 Update PPP, Fix Bug, Testing for IncompleteCommand
  docs/team/anqi20.md
  src/main/java/seedu/eduke8/question/QuestionList.java
  src/test/java/seedu/eduke8/command/IncompleteCommandTest.java
Labels: priority.Medium

#255 Add java docs + JUnits Test + Fixed a bug
  src/main/java/seedu/eduke8/note/Note.java
  src/main/java/seedu/eduke8/note/NoteList.java
  src/main/java/seedu/eduke8/topic/Topic.java
  src/main/java/seedu/eduke8/topic/TopicList.java
  src/main/java/seedu/eduke8/ui/Ui.java
  src/test/java/seedu/eduke8/note/NoteListTest.java
  src/test/java/seedu/eduke8/note/NoteTest.java
  src/test/java/seedu/eduke8/topic/TopicListTest.java
Labels: priority.Medium

#262 Add amendments to ui
  src/main/java/seedu/eduke8/ui/Ui.java
Labels: priority.Medium

#264 Add json to resources as a fallback
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kstonekuan.md
  src/main/java/seedu/eduke8/Eduke8.java
  src/main/java/seedu/eduke8/storage/LocalStorage.java
  src/main/java/seedu/eduke8/storage/TopicsStorage.java
  src/main/java/seedu/eduke8/storage/UserStorage.java
  src/main/resources/topics.json
  src/test/java/seedu/eduke8/storage/TopicsStorageTest.java
Labels: severity.Medium, type.Enhancement
